/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvSlugRouteImport } from './routes/tv.$slug'
import { Route as PersonSlugRouteImport } from './routes/person.$slug'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'

const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSlugRoute = TvSlugRouteImport.update({
  id: '/tv/$slug',
  path: '/tv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonSlugRoute = PersonSlugRouteImport.update({
  id: '/person/$slug',
  path: '/person/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/shows': typeof ShowsRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/tv/$slug': typeof TvSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/shows': typeof ShowsRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/tv/$slug': typeof TvSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/shows': typeof ShowsRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/tv/$slug': typeof TvSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movies'
    | '/search'
    | '/shows'
    | '/collection/$slug'
    | '/movie/$slug'
    | '/person/$slug'
    | '/tv/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movies'
    | '/search'
    | '/shows'
    | '/collection/$slug'
    | '/movie/$slug'
    | '/person/$slug'
    | '/tv/$slug'
  id:
    | '__root__'
    | '/'
    | '/movies'
    | '/search'
    | '/shows'
    | '/collection/$slug'
    | '/movie/$slug'
    | '/person/$slug'
    | '/tv/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoviesRoute: typeof MoviesRoute
  SearchRoute: typeof SearchRoute
  ShowsRoute: typeof ShowsRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  MovieSlugRoute: typeof MovieSlugRoute
  PersonSlugRoute: typeof PersonSlugRoute
  TvSlugRoute: typeof TvSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$slug': {
      id: '/tv/$slug'
      path: '/tv/$slug'
      fullPath: '/tv/$slug'
      preLoaderRoute: typeof TvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$slug': {
      id: '/person/$slug'
      path: '/person/$slug'
      fullPath: '/person/$slug'
      preLoaderRoute: typeof PersonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoviesRoute: MoviesRoute,
  SearchRoute: SearchRoute,
  ShowsRoute: ShowsRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  MovieSlugRoute: MovieSlugRoute,
  PersonSlugRoute: PersonSlugRoute,
  TvSlugRoute: TvSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
